# Generated by Django 4.1.5 on 2023-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
